name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Demo App Dependencies
      run: pip install -r demo_app/requirements.txt

    - name: Test Demo App
      run: pytest demo_app/test_app.py

    - name: Install Monitor API Dependencies
      run: pip install -r monitor_api/requirements.txt

    - name: Test Monitor API
      run: pytest monitor_api/test_api.py
